global:
  scrape_interval: 15s #interval to scrap the metrics

scrape_configs:
  - job_name: 'edgeAgent'
    static_configs:
      - targets: ['localhost:9601'] #host IP to scrap the inbuilt edge agent metrics
      
  - job_name: 'edgeHub'
    static_configs:
      - targets: ['localhost:9602'] #host IP to scrap the custom peripheral metrics

  - job_name: 'peripheral-exporter'
    static_configs:
      - targets: ['localhost:9093'] #host IP to scrap the custom peripheral metrics
        labels: 
          edge_device: '<dynamic-value>'  #add custom label (device name) to the metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']  #third party exporter to scrap the host device metrics
        labels: 
          edge_device: '<dynamic-value>' #add custom label (device name) to the metrics

# remote_write:
# - url: <dynamic-value> # URL to remote write
#   basic_auth:
#     username: <dynamic-value>
#     password: <dynamic-value>


